# Generated by Django 4.1.1 on 2022-10-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="snippet", name="highlighted", field=models.TextField(),
        ),
    ]
